/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package gui;

// Mengimpor kelas dbCRUD dari paket kebudayaan, digunakan untuk operasi CRUD pada database
import kebudayaan.dbCRUD;

// Mengimpor kelas Statement dari java.sql untuk membuat dan menjalankan pernyataan SQL
import java.sql.Statement;

// Mengimpor JOptionPane dari javax.swing untuk menampilkan dialog pesan kepada pengguna
import javax.swing.JOptionPane;

// Mengimpor kelas Level dari java.util.logging untuk mendefinisikan tingkat log (seperti SEVERE, WARNING, INFO)
import java.util.logging.Level;

// Mengimpor kelas Logger dari java.util.logging untuk mencatat log aktivitas aplikasi
import java.util.logging.Logger;


/**
 *
 * @author ACER
 */
public class Kebudayaan extends javax.swing.JFrame {

    // Deklarasi objek CRUD dari kelas dbCRUD untuk melakukan operasi database
    dbCRUD CRUD;

    // Array judulKolom berisi nama-nama kolom yang akan digunakan untuk header tabel
    String judulKolom[] = {"ID KEBUDAYAAN", "NAMA KEBUDAYAAN", "DESKRIPSI"}; 

    // Array lebarKolom berisi ukuran lebar setiap kolom tabel untuk keperluan tata letak
    int lebarKolom[] = {100, 200, 200, 500};

    // Query SQL untuk mengambil semua data dari tabel `kebudayaan`
    String SQL = "SELECT * FROM kebudayaan ";

    
    private void cariData(String cari) {
    String sqlCari;
    try {
        // Periksa apakah input pencarian kosong
        if (cari == null || cari.trim().isEmpty()) {
            sqlCari = "SELECT * FROM kebudayaan"; // Menampilkan semua data
        } else {
            String keyword = txtlaporan.getText().trim(); // Ambil teks dari input laporan
            sqlCari = "SELECT * FROM kebudayaan WHERE " +
                      "id_kebudayaan LIKE '%" + cari + "%' " + // Mencari data di kolom `id_kebudayaan` yang mengandung teks dari variabel `cari`
                      "OR nama_kebudayaan LIKE '%" + keyword + "%' " +
                      "OR deskripsi LIKE '%" + keyword + "%'";
            // LIKE : Operator SQL yang mencocokkan nilai kolom dengan pola tertentu.
            // '% : adalah wildcard SQL yang mencocokkan nol atau lebih karakter sebelum teks pencarian.
            // keyword dan cari : Variabel Java yang berisi teks pencarian yang ingin dicocokkan.
            // %' : adalah variabel setelah teks pencarian mencocokkan nol atau lebih karakter setelah teks pencarian.
            // + : Operator Java untuk menggabungkan string dalam query.
        }

        // Mengatur judul tabel
        CRUD.settingJudulTabel(jTable2, judulKolom);
        
        // Menampilkan data pada JTable
        CRUD.tampilTabel(jTable2, sqlCari, judulKolom);
        
        // Mengatur lebar kolom
        CRUD.settingLebarKolom(jTable2, lebarKolom);

    } catch (Exception e) {
        // Menangani error dan mencetak pesan error ke konsol
        System.err.println("Error saat mencari data: " + e.getMessage());
    }
}

    
    /**
     * Creates new form Kebudayaan
     */
    public Kebudayaan() {
        initComponents(); // Menginisialisasi semua komponen GUI (seperti tombol, tabel, label, dan lainnya) yang ada di JFrame atau JPanel.
        CRUD = new dbCRUD(); // Membuat instance dari class dbCRUD untuk menangani operasi database (seperti koneksi, eksekusi query, dan manipulasi data).
        loaddata(); // Memanggil metode loaddata untuk memuat dan menampilkan data dari database ke dalam tabel jTable2.
    }
    
    public void loaddata (){
        CRUD.settingJudulTabel(jTable2, judulKolom); // Mengatur header kolom tabel jTable2 sesuai dengan array judulKolom.
        CRUD.settingLebarKolom(jTable2, lebarKolom); // Mengatur lebar kolom tabel jTable2 sesuai dengan array lebarKolom.
        CRUD.tampilTabel(jTable2, SQL, judulKolom); // Menampilkan data dari database ke dalam tabel jTable2 menggunakan query SQL dan mencocokkannya dengan header kolom di judulKolom.
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        txtid_kebudayaan = new javax.swing.JTextField();
        txtnama_kebudayaan = new javax.swing.JTextField();
        txtdeskripsi = new javax.swing.JTextField();
        bsimpan = new javax.swing.JButton();
        bedit = new javax.swing.JButton();
        bhapus = new javax.swing.JButton();
        bkembali = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable2 = new javax.swing.JTable();
        jLabel4 = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        txtlaporan = new javax.swing.JTextPane();
        jButton5 = new javax.swing.JButton();
        bbersih = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("ID KEBUDAYAAN        :");

        jLabel2.setText("NAMA KEBUDAYAAN :");

        jLabel3.setText("DESKRIPSI                   :");

        txtdeskripsi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtdeskripsiActionPerformed(evt);
            }
        });

        bsimpan.setText("SIMPAN");
        bsimpan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bsimpanActionPerformed(evt);
            }
        });

        bedit.setText("UBAH");
        bedit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                beditActionPerformed(evt);
            }
        });

        bhapus.setText("HAPUS");
        bhapus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bhapusActionPerformed(evt);
            }
        });

        bkembali.setText("KEMBALI");
        bkembali.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bkembaliActionPerformed(evt);
            }
        });

        jTable2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jTable2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable2MouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(jTable2);

        jLabel4.setText("CARI DATA :");

        txtlaporan.addAncestorListener(new javax.swing.event.AncestorListener() {
            public void ancestorAdded(javax.swing.event.AncestorEvent evt) {
                txtlaporanAncestorAdded(evt);
            }
            public void ancestorMoved(javax.swing.event.AncestorEvent evt) {
            }
            public void ancestorRemoved(javax.swing.event.AncestorEvent evt) {
            }
        });
        txtlaporan.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtlaporanKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtlaporanKeyReleased(evt);
            }
        });
        jScrollPane3.setViewportView(txtlaporan);

        jButton5.setText("CETAK");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });
        jButton5.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jButton5KeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jButton5KeyReleased(evt);
            }
        });

        bbersih.setText("BERSIH");
        bbersih.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bbersihActionPerformed(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Segoe UI", 3, 36)); // NOI18N
        jLabel5.setText("KEBUDAYAAN");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(jLabel2)
                                .addComponent(jLabel1))
                            .addComponent(jLabel3))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtdeskripsi)
                            .addComponent(txtnama_kebudayaan)
                            .addComponent(txtid_kebudayaan, javax.swing.GroupLayout.Alignment.TRAILING)))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addComponent(bsimpan)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(bedit)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(bhapus)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(bkembali)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(bbersih)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 249, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton5, javax.swing.GroupLayout.DEFAULT_SIZE, 82, Short.MAX_VALUE)))
                .addGap(21, 21, 21))
            .addGroup(layout.createSequentialGroup()
                .addGap(99, 99, 99)
                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 257, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txtid_kebudayaan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addComponent(txtnama_kebudayaan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txtdeskripsi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(bsimpan)
                    .addComponent(bedit)
                    .addComponent(bhapus)
                    .addComponent(bkembali)
                    .addComponent(bbersih))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(12, 12, 12)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButton5)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jScrollPane3, javax.swing.GroupLayout.Alignment.LEADING)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtdeskripsiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtdeskripsiActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtdeskripsiActionPerformed

    private void bsimpanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bsimpanActionPerformed
        String[] field ={"id_kebudayaan", "nama_kebudayaan", "deskripsi"}; // Mendefinisikan array `field` yang berisi nama-nama kolom dalam tabel database (tabel `kebudayaan`).
        String[] Isi ={txtid_kebudayaan.getText(),txtnama_kebudayaan.getText(),txtdeskripsi.getText()}; // Membuat array `Isi` yang berisi nilai-nilai yang diambil dari text field GUI 
        // (txtid_kebudayaan, txtnama_kebudayaan, dan txtdeskripsi) untuk dimasukkan ke database.
        new dbCRUD().SimpanDinamis("kebudayaan",field,Isi);
        // Memanggil metode `SimpanDinamis` dari class `dbCRUD` untuk menyimpan data secara dinamis ke tabel `kebudayaan`.
        // - Argumen pertama: "kebudayaan" adalah nama tabel di database.
        // - Argumen kedua: `field` adalah array nama-nama kolom yang akan diisi.
        // - Argumen ketiga: `Isi` adalah array nilai-nilai yang akan disimpan ke kolom tersebut.
        loaddata(); // Memanggil metode `loaddata()` untuk memuat ulang data di tabel GUI (`jTable2`) setelah data baru berhasil disimpan.   
    }//GEN-LAST:event_bsimpanActionPerformed

    private void beditActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_beditActionPerformed
        String[] field = {"id_kebudayaan", "nama_kebudayaan", "deskripsi"}; // Mendefinisikan array `field` yang berisi nama-nama kolom yang akan diperbarui.
        String[] Isi = {txtid_kebudayaan.getText(), txtnama_kebudayaan.getText(), txtdeskripsi.getText()}; // Membuat array `Isi` yang berisi nilai-nilai baru untuk kolom yang akan diperbarui.
        CRUD.UbahDinamis("kebudayaan", "id_kebudayaan", txtid_kebudayaan.getText(), field, Isi); 
        // Memanggil metode `UbahDinamis` dari class `CRUD` untuk memperbarui data di database.
        // - Argumen pertama: "kebudayaan" adalah nama tabel yang akan diperbarui.
        // - Argumen kedua: "id_kebudayaan" adalah kolom kunci utama untuk identifikasi data.
        // - Argumen ketiga: `txtid_kebudayaan.getText()` adalah nilai kunci utama untuk data yang akan diubah.
        // - Argumen keempat: `field` adalah array nama-nama kolom yang akan diperbarui.
        // - Argumen kelima: `Isi` adalah array nilai-nilai baru untuk kolom tersebut.
        JOptionPane.showMessageDialog(null, "Data Berhasil Diubah"); // Menampilkan dialog pemberitahuan bahwa data berhasil diubah.
        loaddata(); // Memanggil metode `loaddata()` untuk memperbarui isi tabel di GUI agar mencerminkan data terbaru.
    }//GEN-LAST:event_beditActionPerformed

    private void bhapusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bhapusActionPerformed
        CRUD.HapusDinamis("kebudayaan", "id_kebudayaan", txtid_kebudayaan.getText());
        // Memanggil metode `HapusDinamis` dari class `CRUD` untuk menghapus data di database.
        // - Argumen pertama: "kebudayaan" adalah nama tabel yang akan dihapus datanya.
        // - Argumen kedua: "id_kebudayaan" adalah kolom kunci utama untuk identifikasi data.
        // - Argumen ketiga: `txtid_kebudayaan.getText()` adalah nilai kunci utama untuk data yang akan dihapus.
        JOptionPane.showMessageDialog(null, "Data berhasil dihapus"); // Menampilkan dialog pemberitahuan bahwa data berhasil dihapus.
        loaddata(); // Memanggil metode `loaddata()` untuk memperbarui isi tabel di GUI agar mencerminkan data terbaru setelah penghapusan.
    }//GEN-LAST:event_bhapusActionPerformed

    private void bkembaliActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bkembaliActionPerformed
        Home home = new Home(); // Membuat objek baru dari kelas Home, yang merupakan jendela utama aplikasi.
        home.setVisible(true); // Menampilkan jendela Home kepada pengguna, sehingga terlihat di layar.
        this.dispose(); // Menutup jendela saat ini untuk menghemat resource tanpa menghentikan seluruh aplikasi.
    }//GEN-LAST:event_bkembaliActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
    try {
    // Mengecek apakah teks di txtlaporan kosong.
    if (txtlaporan.getText().isEmpty()) {
        // Jika txtlaporan kosong, tampilkan semua data dari tabel kebudayaan 
        // menggunakan file laporan Kebudayaan.jrxml.
        CRUD.tampilLaporan("src/laporan/Kebudayaan.jrxml", "SELECT*FROM kebudayaan");
    } else {
        // Jika txtlaporan tidak kosong, buat query SQL untuk mencari data.
        // Data difilter berdasarkan id_kebudayaan, nama_kebudayaan, atau deskripsi
        // yang sesuai dengan input pada txtlaporan.
        String sql = "select*from kebudayaan where id_kebudayaan='" + txtlaporan.getText() + "'" +
                     " or nama_kebudayaan='" + txtlaporan.getText() + "'" +
                     " or deskripsi='" + txtlaporan.getText() + "'";
        
        // Tampilkan laporan menggunakan file Kebudayaan.jrxml dengan query hasil filter.
        CRUD.tampilLaporan("src/laporan/Kebudayaan.jrxml", sql);
    }
} catch (Exception ex) {
    // Jika terjadi kesalahan, tulis log error dengan detail exception.
    Logger.getLogger(Kebudayaan.class.getName()).log(Level.SEVERE, null, ex);
}

    }//GEN-LAST:event_jButton5ActionPerformed

    private void jButton5KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jButton5KeyReleased
    // TODO add your handling code here:
    }//GEN-LAST:event_jButton5KeyReleased

    private void jButton5KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jButton5KeyPressed
    // TODO add your handling code here:
    }//GEN-LAST:event_jButton5KeyPressed

    private void txtlaporanAncestorAdded(javax.swing.event.AncestorEvent evt) {//GEN-FIRST:event_txtlaporanAncestorAdded
    // TODO add your handling code here:
    }//GEN-LAST:event_txtlaporanAncestorAdded

    private void bbersihActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bbersihActionPerformed
        // Kosongkan semua field teks
        txtid_kebudayaan.setText("");
        txtnama_kebudayaan.setText("");
        txtdeskripsi.setText("");
        // Fokuskan kembali pada field pertama
        txtid_kebudayaan.requestFocus();
    }//GEN-LAST:event_bbersihActionPerformed

    private void jTable2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable2MouseClicked
        // Mendapatkan indeks baris dari tabel jTable2 berdasarkan lokasi klik (evt.getPoint()).
        int baris = jTable2.rowAtPoint(evt.getPoint());

        // Mengambil data dari kolom ke-1 (indeks 1) pada baris yang diklik.
        // Data ini diambil sebagai String dan diatur ke dalam text field txtid_kebudayaan.
        String id_kebudayaan = jTable2.getValueAt(baris, 1).toString();
        txtid_kebudayaan.setText(id_kebudayaan);

        // Mengambil data dari kolom ke-2 (indeks 2) pada baris yang diklik.
        // Data ini diambil sebagai String dan diatur ke dalam text field txtnama_kebudayaan.
        String nama_kebudayaan = jTable2.getValueAt(baris, 2).toString();
        txtnama_kebudayaan.setText(nama_kebudayaan);

        // Mengambil data dari kolom ke-3 (indeks 3) pada baris yang diklik.
        // Data ini diambil sebagai String dan diatur ke dalam text field txtdeskripsi.
        String deskripsi = jTable2.getValueAt(baris, 3).toString();
        txtdeskripsi.setText(deskripsi);
    }//GEN-LAST:event_jTable2MouseClicked

    private void txtlaporanKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtlaporanKeyReleased
    cariData(txtlaporan.getText()); // Memanggil metode cariData dan memberikan teks yang diambil dari txtlaporan sebagai parameter(variabel dalam fungsi atau metode yang menerima input dari luar untuk menjalankan fungsi tersebut).
    }//GEN-LAST:event_txtlaporanKeyReleased

    private void txtlaporanKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtlaporanKeyPressed
    cariData(txtlaporan.getText());
    }//GEN-LAST:event_txtlaporanKeyPressed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Kebudayaan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Kebudayaan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Kebudayaan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Kebudayaan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
            // Membuat instance baru dari kelas Kebudayaan.
            new Kebudayaan()
            // Menampilkan jendela GUI Kebudayaan ke layar.
            .setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bbersih;
    private javax.swing.JButton bedit;
    private javax.swing.JButton bhapus;
    private javax.swing.JButton bkembali;
    private javax.swing.JButton bsimpan;
    private javax.swing.JButton jButton5;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTable jTable1;
    private javax.swing.JTable jTable2;
    private javax.swing.JTextField txtdeskripsi;
    private javax.swing.JTextField txtid_kebudayaan;
    private javax.swing.JTextPane txtlaporan;
    private javax.swing.JTextField txtnama_kebudayaan;
    // End of variables declaration//GEN-END:variables
}
